import { Deck } from './types';
// Generated by scripts/build-ja-jlpt.py from open-anki-jlpt-decks (MIT),
// romaji via pykakasi, frequency-sorted within each JLPT level. Levels gate
// sequentially (finish N5 to open N4). Never re-sort: ids are position-based
// and reordering would detach them from saved FSRS progress.
import data from './ja-jlpt.json';

export const jaJlpt: Deck = {
  lang: 'ja',
  langLabel: 'Japanese',
  ttsLocale: 'ja-JP',
  scenarios: data.scenarios,
  items: data.items as Deck['items'],
};
