import { Deck } from './types';
// Generated by scripts/build-hsk-deck.js — HSK 1-4 ladder (1,156 words,
// survival-deck duplicates excluded). Regenerate rather than hand-edit.
import deckJson from './zh-hsk.json';

export const zhHsk = deckJson as Deck;
